import type {
  CorpusCase,
  CorpusSeedFile,
  TaskCorpus,
} from "../../scripts/run-harness-task-corpus.ts";

interface CaseDefinition {
  id: string;
  category: string;
  task: string;
  initial: string;
  reference: string;
  tests: string;
  maxSteps?: number;
  maxTokens?: number;
}

const AIDER_SOURCE = {
  family: "aider-polyglot",
  reference: "https://github.com/Aider-AI/polyglot-benchmark",
  adaptation: "shape_derived" as const,
};

const SWE_BENCH_SOURCE = {
  family: "swe-bench",
  reference: "https://github.com/SWE-bench/SWE-bench",
  adaptation: "shape_derived" as const,
};

const SWE_MULTILINGUAL_SOURCE = {
  family: "swe-bench-multilingual",
  reference: "https://github.com/swe-bench/SWE-bench_Multilingual",
  adaptation: "shape_derived" as const,
};

const REACT_BENCH_SOURCE = {
  family: "react-bench",
  reference: "https://www.reactbench.com/",
  adaptation: "behavior_derived" as const,
};

const RUST_LOCK = `
  # This file is automatically @generated by Cargo.
  # It is not intended for manual editing.
  version = 4

  [[package]]
  name = "usability_fixture"
  version = "0.1.0"
`;

const REACT_LOCK = `
  {
    "version": "5",
    "specifiers": {
      "npm:@types/react-dom@19.2.3": "19.2.3_@types+react@19.2.17",
      "npm:@types/react@19.2.17": "19.2.17",
      "npm:react-dom@19.2.7": "19.2.7_react@19.2.7",
      "npm:react@19.2.7": "19.2.7"
    },
    "npm": {
      "@types/react-dom@19.2.3_@types+react@19.2.17": {
        "integrity": "sha512-jp2L/eY6fn+KgVVQAOqYItbF0VY/YApe5Mz2F0aykSO8gx31bYCZyvSeYxCHKvzHG5eZjc+zyaS5BrBWya2+kQ==",
        "dependencies": ["@types/react"]
      },
      "@types/react@19.2.17": {
        "integrity": "sha512-MXfmqaVPEVgkBT/aY0aGCkRWWtByiYQXo3xdQ8r5RzuFrPiRn8Gar2tQdXSUQ2GKV3bkXckek89V8wQBY2Q/Aw==",
        "dependencies": ["csstype"]
      },
      "csstype@3.2.3": {
        "integrity": "sha512-z1HGKcYy2xA8AGQfwrn0PAy+PB7X/GSj3UVJW9qKyn43xWa+gl5nXmU4qqLMRzWVLFC8KusUX8T/0kCiOYpAIQ=="
      },
      "react-dom@19.2.7_react@19.2.7": {
        "integrity": "sha512-t0BRVXvbiE/o20Hfw669rLbMCDWtYZLvmJigy2f0MxsXF+71pxhR3xOkspmsO8h3ZlNzyibAmtCa3l4lYKk6gQ==",
        "dependencies": ["react", "scheduler"]
      },
      "react@19.2.7": {
        "integrity": "sha512-HNe9WslTbXmFK8o8cmwgAeJFSBvt1bPdHCVKtaaV+WlAN36mpT4hcRpwbf3fY56ar2oIXzsBpOAiIRHAdY0OlQ=="
      },
      "scheduler@0.27.0": {
        "integrity": "sha512-eNv+WrVbKu1f3vbYJT/xtiF5syA5HPIMtf9IgY/nKg0sWqzAUEvqY/xm7OcZc/qafLx/iO9FgOmeSAp4v5ti/Q=="
      }
    },
    "workspace": {
      "dependencies": [
        "npm:@types/react-dom@19.2.3",
        "npm:@types/react@19.2.17",
        "npm:react-dom@19.2.7",
        "npm:react@19.2.7"
      ]
    }
  }
`;

function normalizedContent(content: string): string {
  const lines = content.split("\n");
  while (lines[0]?.trim().length === 0) lines.shift();
  while (lines.at(-1)?.trim().length === 0) lines.pop();
  const indentation = Math.min(
    ...lines.filter((line) => line.trim().length > 0).map((line) =>
      line.length - line.trimStart().length
    ),
  );
  return lines.map((line) => line.slice(indentation)).join("\n");
}

function file(path: string, content: string): CorpusSeedFile {
  return { path, content: `${normalizedContent(content)}\n` };
}

function contract(path: string, command: string): Record<string, unknown> {
  return {
    version: 1,
    mutation: "required",
    allowed_paths: [path],
    work_unit_guidance: {},
    checks: [{
      id: "behavior",
      command,
      cwd: ".",
      required: true,
      diagnostic_eligible: true,
      timeout_seconds: 60,
    }],
    commit: { required: true, semantic: true },
    review: {
      required: true,
      read_paths: [path],
      check_ids: ["behavior"],
    },
    workspace_clean: true,
  };
}

function rustCase(
  definition: CaseDefinition,
  source: typeof AIDER_SOURCE | typeof SWE_MULTILINGUAL_SOURCE,
): CorpusCase {
  return {
    id: definition.id,
    category: definition.category,
    language: "rust",
    source,
    task: definition.task,
    seed_files: [
      file(
        "Cargo.toml",
        `
        [package]
        name = "usability_fixture"
        version = "0.1.0"
        edition = "2021"

        [dependencies]
      `,
      ),
      file("Cargo.lock", RUST_LOCK),
      file(".gitignore", "/target/"),
      file("src/lib.rs", definition.initial),
      file("tests/behavior.rs", definition.tests),
    ],
    resume_files: [],
    reference_files: [file("src/lib.rs", definition.reference)],
    contract: contract(
      "src/lib.rs",
      "cargo test --offline --locked --quiet",
    ),
    limits: {
      max_steps: definition.maxSteps ?? 7,
      max_tokens: definition.maxTokens ?? 1792,
    },
  };
}

function pythonCase(
  definition: CaseDefinition,
  source: typeof AIDER_SOURCE | typeof SWE_BENCH_SOURCE,
): CorpusCase {
  return {
    id: definition.id,
    category: definition.category,
    language: "python",
    source,
    task: definition.task,
    seed_files: [
      file(".gitignore", "__pycache__/\n*.pyc"),
      file(
        "app.py",
        `from __future__ import annotations\n\n${
          normalizedContent(definition.initial)
        }`,
      ),
      file("tests/test_behavior.py", definition.tests),
    ],
    resume_files: [],
    reference_files: [
      file(
        "app.py",
        `from __future__ import annotations\n\n${
          normalizedContent(definition.reference)
        }`,
      ),
    ],
    contract: contract(
      "app.py",
      "python3 -m unittest discover -s tests -p 'test_*.py'",
    ),
    limits: {
      max_steps: definition.maxSteps ?? 7,
      max_tokens: definition.maxTokens ?? 1792,
    },
  };
}

function reactCase(definition: CaseDefinition): CorpusCase {
  return {
    id: definition.id,
    category: definition.category,
    language: "react_typescript",
    source: REACT_BENCH_SOURCE,
    task: definition.task,
    seed_files: [
      file(
        "deno.json",
        `
        {
          "imports": {
            "react": "npm:react@19.2.7",
            "react/jsx-runtime": "npm:react@19.2.7/jsx-runtime",
            "react-dom/server": "npm:react-dom@19.2.7/server"
          },
          "compilerOptions": {
            "jsx": "react-jsx",
            "jsxImportSource": "react",
            "types": [
              "npm:@types/react@19.2.17",
              "npm:@types/react-dom@19.2.3"
            ],
            "lib": ["deno.window", "dom"]
          }
        }
      `,
      ),
      file("deno.lock", REACT_LOCK),
      file("src/Component.tsx", definition.initial),
      file("tests/component_test.tsx", definition.tests),
    ],
    resume_files: [],
    reference_files: [file("src/Component.tsx", definition.reference)],
    contract: contract(
      "src/Component.tsx",
      "deno test --cached-only --frozen --allow-read --allow-env=NODE_ENV",
    ),
    limits: {
      max_steps: definition.maxSteps ?? 7,
      max_tokens: definition.maxTokens ?? 1792,
    },
  };
}

const rustCases: CorpusCase[] = [
  rustCase({
    id: "rust_run_length_encoding",
    category: "compact_algorithm_repair",
    task:
      "Repair run-length encoding so consecutive Unicode scalar values are encoded as count followed by character. Empty input must stay empty.",
    initial: `
      pub fn encode(input: &str) -> String {
          input.to_owned()
      }
    `,
    reference: `
      pub fn encode(input: &str) -> String {
          let mut chars = input.chars();
          let Some(mut current) = chars.next() else {
              return String::new();
          };
          let mut count = 1usize;
          let mut encoded = String::new();
          for character in chars {
              if character == current {
                  count += 1;
              } else {
                  encoded.push_str(&count.to_string());
                  encoded.push(current);
                  current = character;
                  count = 1;
              }
          }
          encoded.push_str(&count.to_string());
          encoded.push(current);
          encoded
      }
    `,
    tests: `
      use usability_fixture::encode;

      #[test]
      fn encodes_runs_and_boundaries() {
          assert_eq!(encode(""), "");
          assert_eq!(encode("aaabbc"), "3a2b1c");
          assert_eq!(encode("z"), "1z");
          assert_eq!(encode("éé🙂🙂🙂"), "2é3🙂");
      }
    `,
  }, AIDER_SOURCE),
  rustCase({
    id: "rust_roman_numerals",
    category: "compact_algorithm_repair",
    task:
      "Implement canonical Roman numeral formatting for values 1 through 3999. Return an empty string for values outside that range.",
    initial: `
      pub fn roman(value: u32) -> String {
          value.to_string()
      }
    `,
    reference: `
      pub fn roman(mut value: u32) -> String {
          if !(1..=3999).contains(&value) {
              return String::new();
          }
          let symbols = [
              (1000, "M"), (900, "CM"), (500, "D"), (400, "CD"),
              (100, "C"), (90, "XC"), (50, "L"), (40, "XL"),
              (10, "X"), (9, "IX"), (5, "V"), (4, "IV"), (1, "I"),
          ];
          let mut result = String::new();
          for (amount, symbol) in symbols {
              while value >= amount {
                  value -= amount;
                  result.push_str(symbol);
              }
          }
          result
      }
    `,
    tests: `
      use usability_fixture::roman;

      #[test]
      fn formats_canonical_values() {
          assert_eq!(roman(0), "");
          assert_eq!(roman(4), "IV");
          assert_eq!(roman(944), "CMXLIV");
          assert_eq!(roman(3999), "MMMCMXCIX");
          assert_eq!(roman(4000), "");
      }
    `,
  }, AIDER_SOURCE),
  rustCase({
    id: "rust_config_precedence",
    category: "repository_logic_repair",
    task:
      "Fix configuration merging so defaults are overridden by project values and project values are overridden by environment values.",
    initial: `
      use std::collections::BTreeMap;

      pub fn merge(
          defaults: &[(&str, &str)],
          project: &[(&str, &str)],
          environment: &[(&str, &str)],
      ) -> BTreeMap<String, String> {
          let mut result = BTreeMap::new();
          for (key, value) in environment.iter().chain(project).chain(defaults) {
              result.insert((*key).to_owned(), (*value).to_owned());
          }
          result
      }
    `,
    reference: `
      use std::collections::BTreeMap;

      pub fn merge(
          defaults: &[(&str, &str)],
          project: &[(&str, &str)],
          environment: &[(&str, &str)],
      ) -> BTreeMap<String, String> {
          let mut result = BTreeMap::new();
          for (key, value) in defaults.iter().chain(project).chain(environment) {
              result.insert((*key).to_owned(), (*value).to_owned());
          }
          result
      }
    `,
    tests: `
      use usability_fixture::merge;

      #[test]
      fn applies_precedence_without_dropping_keys() {
          let merged = merge(
              &[("host", "localhost"), ("port", "80")],
              &[("port", "8080"), ("mode", "project")],
              &[("mode", "private")],
          );
          assert_eq!(merged.get("host").map(String::as_str), Some("localhost"));
          assert_eq!(merged.get("port").map(String::as_str), Some("8080"));
          assert_eq!(merged.get("mode").map(String::as_str), Some("private"));
      }
    `,
  }, SWE_MULTILINGUAL_SOURCE),
  rustCase({
    id: "rust_bounded_backoff",
    category: "edge_case_repair",
    task:
      "Make exponential backoff saturating and capped. Large attempt counts must never panic or wrap, and the result must never exceed the cap.",
    initial: `
      pub fn delay_ms(base: u64, attempt: u32, cap: u64) -> u64 {
          base * (1_u64 << attempt)
      }
    `,
    reference: `
      pub fn delay_ms(base: u64, attempt: u32, cap: u64) -> u64 {
          let multiplier = 1_u64.checked_shl(attempt).unwrap_or(u64::MAX);
          base.saturating_mul(multiplier).min(cap)
      }
    `,
    tests: `
      use usability_fixture::delay_ms;

      #[test]
      fn caps_and_saturates() {
          assert_eq!(delay_ms(100, 0, 10_000), 100);
          assert_eq!(delay_ms(100, 3, 10_000), 800);
          assert_eq!(delay_ms(100, 20, 5_000), 5_000);
          assert_eq!(delay_ms(u64::MAX, 2, u64::MAX), u64::MAX);
          assert_eq!(delay_ms(1, 80, 4_000), 4_000);
      }
    `,
  }, SWE_MULTILINGUAL_SOURCE),
  rustCase({
    id: "rust_registry_removal",
    category: "state_management_repair",
    task:
      "Repair Registry::remove so it returns the removed value and actually removes the key. Removing an unknown key must leave the registry unchanged.",
    initial: `
      use std::collections::BTreeMap;

      #[derive(Default)]
      pub struct Registry {
          entries: BTreeMap<String, String>,
      }

      impl Registry {
          pub fn insert(&mut self, key: impl Into<String>, value: impl Into<String>) {
              self.entries.insert(key.into(), value.into());
          }

          pub fn remove(&mut self, key: &str) -> Option<String> {
              self.entries.get(key).cloned()
          }

          pub fn get(&self, key: &str) -> Option<&str> {
              self.entries.get(key).map(String::as_str)
          }

          pub fn len(&self) -> usize {
              self.entries.len()
          }
      }
    `,
    reference: `
      use std::collections::BTreeMap;

      #[derive(Default)]
      pub struct Registry {
          entries: BTreeMap<String, String>,
      }

      impl Registry {
          pub fn insert(&mut self, key: impl Into<String>, value: impl Into<String>) {
              self.entries.insert(key.into(), value.into());
          }

          pub fn remove(&mut self, key: &str) -> Option<String> {
              self.entries.remove(key)
          }

          pub fn get(&self, key: &str) -> Option<&str> {
              self.entries.get(key).map(String::as_str)
          }

          pub fn len(&self) -> usize {
              self.entries.len()
          }
      }
    `,
    tests: `
      use usability_fixture::Registry;

      #[test]
      fn removal_updates_state() {
          let mut registry = Registry::default();
          registry.insert("alpha", "one");
          registry.insert("beta", "two");
          assert_eq!(registry.remove("alpha").as_deref(), Some("one"));
          assert_eq!(registry.get("alpha"), None);
          assert_eq!(registry.len(), 1);
          assert_eq!(registry.remove("missing"), None);
          assert_eq!(registry.len(), 1);
      }
    `,
  }, SWE_MULTILINGUAL_SOURCE),
  rustCase({
    id: "rust_quoted_csv",
    category: "parser_repair",
    task:
      "Fix the single-line CSV parser to preserve commas inside quoted fields and decode doubled quote escapes. Quotes are delimiters, not output characters.",
    initial: `
      pub fn parse_line(line: &str) -> Vec<String> {
          line.split(',').map(str::to_owned).collect()
      }
    `,
    reference: `
      pub fn parse_line(line: &str) -> Vec<String> {
          let mut fields = Vec::new();
          let mut field = String::new();
          let mut quoted = false;
          let mut chars = line.chars().peekable();
          while let Some(character) = chars.next() {
              match character {
                  '"' if quoted && chars.peek() == Some(&'"') => {
                      chars.next();
                      field.push('"');
                  }
                  '"' => quoted = !quoted,
                  ',' if !quoted => fields.push(std::mem::take(&mut field)),
                  other => field.push(other),
              }
          }
          fields.push(field);
          fields
      }
    `,
    tests: String.raw`
      use usability_fixture::parse_line;

      #[test]
      fn parses_quotes_and_empty_fields() {
          assert_eq!(parse_line("a,b,c"), ["a", "b", "c"]);
          assert_eq!(parse_line("a,\"b,c\",d"), ["a", "b,c", "d"]);
          assert_eq!(parse_line("\"say \"\"hi\"\"\",,"), ["say \"hi\"", "", ""]);
      }
    `,
  }, SWE_MULTILINGUAL_SOURCE),
  rustCase({
    id: "rust_safe_relative_path",
    category: "security_boundary_repair",
    task:
      "Repair normalize_beneath so absolute paths and traversal above the root are rejected, while safe dot and parent components are normalized beneath the supplied root.",
    initial: `
      use std::path::{Path, PathBuf};

      pub fn normalize_beneath(root: &Path, input: &Path) -> Option<PathBuf> {
          Some(root.join(input))
      }
    `,
    reference: `
      use std::path::{Component, Path, PathBuf};

      pub fn normalize_beneath(root: &Path, input: &Path) -> Option<PathBuf> {
          let mut relative = PathBuf::new();
          for component in input.components() {
              match component {
                  Component::Normal(part) => relative.push(part),
                  Component::CurDir => {}
                  Component::ParentDir => {
                      if !relative.pop() {
                          return None;
                      }
                  }
                  Component::RootDir | Component::Prefix(_) => return None,
              }
          }
          Some(root.join(relative))
      }
    `,
    tests: `
      use std::path::{Path, PathBuf};
      use usability_fixture::normalize_beneath;

      #[test]
      fn confines_paths_lexically() {
          let root = Path::new("/private/work");
          assert_eq!(normalize_beneath(root, Path::new("src/./lib.rs")), Some(PathBuf::from("/private/work/src/lib.rs")));
          assert_eq!(normalize_beneath(root, Path::new("src/../README.md")), Some(PathBuf::from("/private/work/README.md")));
          assert_eq!(normalize_beneath(root, Path::new("../secret")), None);
          assert_eq!(normalize_beneath(root, Path::new("/etc/passwd")), None);
      }
    `,
  }, SWE_MULTILINGUAL_SOURCE),
  rustCase({
    id: "rust_recent_cache_capacity",
    category: "state_management_repair",
    task:
      "Fix RecentCache insertion so updating a key makes it most recent, capacity is enforced by evicting the oldest entry, and capacity zero stores nothing.",
    initial: `
      use std::collections::VecDeque;

      pub struct RecentCache {
          capacity: usize,
          entries: VecDeque<(String, String)>,
      }

      impl RecentCache {
          pub fn new(capacity: usize) -> Self {
              Self { capacity, entries: VecDeque::new() }
          }

          pub fn put(&mut self, key: impl Into<String>, value: impl Into<String>) {
              self.entries.push_back((key.into(), value.into()));
          }

          pub fn get(&self, key: &str) -> Option<&str> {
              self.entries.iter().find(|(candidate, _)| candidate == key).map(|(_, value)| value.as_str())
          }

          pub fn len(&self) -> usize {
              self.entries.len()
          }
      }
    `,
    reference: `
      use std::collections::VecDeque;

      pub struct RecentCache {
          capacity: usize,
          entries: VecDeque<(String, String)>,
      }

      impl RecentCache {
          pub fn new(capacity: usize) -> Self {
              Self { capacity, entries: VecDeque::new() }
          }

          pub fn put(&mut self, key: impl Into<String>, value: impl Into<String>) {
              if self.capacity == 0 {
                  return;
              }
              let key = key.into();
              if let Some(index) = self.entries.iter().position(|(candidate, _)| candidate == &key) {
                  self.entries.remove(index);
              }
              self.entries.push_back((key, value.into()));
              while self.entries.len() > self.capacity {
                  self.entries.pop_front();
              }
          }

          pub fn get(&self, key: &str) -> Option<&str> {
              self.entries.iter().find(|(candidate, _)| candidate == key).map(|(_, value)| value.as_str())
          }

          pub fn len(&self) -> usize {
              self.entries.len()
          }
      }
    `,
    tests: `
      use usability_fixture::RecentCache;

      #[test]
      fn enforces_capacity_and_updates() {
          let mut cache = RecentCache::new(2);
          cache.put("a", "one");
          cache.put("b", "two");
          cache.put("a", "updated");
          cache.put("c", "three");
          assert_eq!(cache.get("a"), Some("updated"));
          assert_eq!(cache.get("b"), None);
          assert_eq!(cache.get("c"), Some("three"));
          assert_eq!(cache.len(), 2);

          let mut disabled = RecentCache::new(0);
          disabled.put("x", "ignored");
          assert_eq!(disabled.len(), 0);
      }
    `,
  }, SWE_MULTILINGUAL_SOURCE),
];

const pythonCases: CorpusCase[] = [
  pythonCase({
    id: "python_luhn_validation",
    category: "compact_algorithm_repair",
    task:
      "Repair Luhn validation for non-empty digit strings. Reject non-digits and return true only when the alternating checksum is divisible by ten.",
    initial: `
      def is_valid(number: str) -> bool:
          return sum(int(character) for character in number) % 10 == 0
    `,
    reference: `
      def is_valid(number: str) -> bool:
          if not number or not number.isascii() or not number.isdigit():
              return False
          digits = [int(character) for character in number]
          parity = len(digits) % 2
          total = 0
          for index, digit in enumerate(digits):
              if index % 2 == parity:
                  digit *= 2
                  if digit > 9:
                      digit -= 9
              total += digit
          return total % 10 == 0
    `,
    tests: `
      import unittest

      from app import is_valid


      class LuhnTests(unittest.TestCase):
          def test_known_values_and_invalid_input(self):
              self.assertTrue(is_valid("79927398713"))
              self.assertTrue(is_valid("0"))
              self.assertFalse(is_valid("79927398714"))
              self.assertFalse(is_valid(""))
              self.assertFalse(is_valid("12 34"))


      if __name__ == "__main__":
          unittest.main()
    `,
  }, AIDER_SOURCE),
  pythonCase({
    id: "python_word_frequency",
    category: "compact_algorithm_repair",
    task:
      "Implement case-insensitive word frequencies. Words are runs of Unicode alphanumeric characters; punctuation and underscores are separators.",
    initial: `
      def frequencies(text: str) -> dict[str, int]:
          return {word: text.split().count(word) for word in text.split()}
    `,
    reference: String.raw`
      import re


      def frequencies(text: str) -> dict[str, int]:
          counts: dict[str, int] = {}
          for word in re.findall(r"[^\W_]+", text.casefold()):
              counts[word] = counts.get(word, 0) + 1
          return counts
    `,
    tests: `
      import unittest

      from app import frequencies


      class FrequencyTests(unittest.TestCase):
          def test_normalizes_words(self):
              self.assertEqual(
                  frequencies("Hello, hello_world! CAFÉ café 42."),
                  {"hello": 2, "world": 1, "café": 2, "42": 1},
              )
              self.assertEqual(frequencies("..."), {})


      if __name__ == "__main__":
          unittest.main()
    `,
  }, AIDER_SOURCE),
  pythonCase({
    id: "python_ttl_cache_boundary",
    category: "state_management_repair",
    task:
      "Fix TTLCache expiration. An entry is expired at its expiry timestamp, expired entries are removed on access, and missing entries return None.",
    initial: `
      class TTLCache:
          def __init__(self) -> None:
              self._entries: dict[str, tuple[object, float]] = {}

          def put(self, key: str, value: object, expires_at: float) -> None:
              self._entries[key] = (value, expires_at)

          def get(self, key: str, now: float) -> object | None:
              entry = self._entries.get(key)
              if entry is None:
                  return None
              value, expires_at = entry
              if now > expires_at:
                  return None
              return value

          def __len__(self) -> int:
              return len(self._entries)
    `,
    reference: `
      class TTLCache:
          def __init__(self) -> None:
              self._entries: dict[str, tuple[object, float]] = {}

          def put(self, key: str, value: object, expires_at: float) -> None:
              self._entries[key] = (value, expires_at)

          def get(self, key: str, now: float) -> object | None:
              entry = self._entries.get(key)
              if entry is None:
                  return None
              value, expires_at = entry
              if now >= expires_at:
                  del self._entries[key]
                  return None
              return value

          def __len__(self) -> int:
              return len(self._entries)
    `,
    tests: `
      import unittest

      from app import TTLCache


      class CacheTests(unittest.TestCase):
          def test_expiration_is_half_open_and_cleans_up(self):
              cache = TTLCache()
              cache.put("token", "private", 10.0)
              self.assertEqual(cache.get("token", 9.999), "private")
              self.assertIsNone(cache.get("token", 10.0))
              self.assertEqual(len(cache), 0)
              self.assertIsNone(cache.get("missing", 0.0))


      if __name__ == "__main__":
          unittest.main()
    `,
  }, SWE_BENCH_SOURCE),
  pythonCase({
    id: "python_retry_policy",
    category: "edge_case_repair",
    task:
      "Repair should_retry. Retry only timeout errors or HTTP 5xx responses, and never retry once the one-based attempt reaches max_attempts.",
    initial: `
      def should_retry(
          error_kind: str | None,
          status: int | None,
          attempt: int,
          max_attempts: int,
      ) -> bool:
          return attempt <= max_attempts and (error_kind is not None or status is not None)
    `,
    reference: `
      def should_retry(
          error_kind: str | None,
          status: int | None,
          attempt: int,
          max_attempts: int,
      ) -> bool:
          if attempt >= max_attempts:
              return False
          return error_kind == "timeout" or (
              status is not None and 500 <= status <= 599
          )
    `,
    tests: `
      import unittest

      from app import should_retry


      class RetryTests(unittest.TestCase):
          def test_retryable_failures_and_attempt_limit(self):
              self.assertTrue(should_retry("timeout", None, 1, 3))
              self.assertTrue(should_retry(None, 503, 2, 3))
              self.assertFalse(should_retry("permission", None, 1, 3))
              self.assertFalse(should_retry(None, 429, 1, 3))
              self.assertFalse(should_retry("timeout", None, 3, 3))
              self.assertFalse(should_retry(None, 503, 4, 3))


      if __name__ == "__main__":
          unittest.main()
    `,
  }, SWE_BENCH_SOURCE),
  pythonCase({
    id: "python_unique_slug_registry",
    category: "state_management_repair",
    task:
      "Fix SlugRegistry.register so names normalize to lowercase ASCII word groups joined by hyphens and collisions receive the first available numeric suffix starting at 2.",
    initial: `
      import re


      class SlugRegistry:
          def __init__(self) -> None:
              self._used: set[str] = set()

          def register(self, name: str) -> str:
              slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
              self._used.add(slug)
              return slug
    `,
    reference: `
      import re


      class SlugRegistry:
          def __init__(self) -> None:
              self._used: set[str] = set()

          def register(self, name: str) -> str:
              base = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
              slug = base
              suffix = 2
              while slug in self._used:
                  slug = f"{base}-{suffix}"
                  suffix += 1
              self._used.add(slug)
              return slug
    `,
    tests: `
      import unittest

      from app import SlugRegistry


      class SlugTests(unittest.TestCase):
          def test_normalization_and_first_available_suffix(self):
              registry = SlugRegistry()
              self.assertEqual(registry.register("Private Workload"), "private-workload")
              self.assertEqual(registry.register("private_workload"), "private-workload-2")
              self.assertEqual(registry.register("private workload"), "private-workload-3")


      if __name__ == "__main__":
          unittest.main()
    `,
  }, SWE_BENCH_SOURCE),
  pythonCase({
    id: "python_deep_config_merge",
    category: "repository_logic_repair",
    task:
      "Repair merge_config so nested dictionaries merge recursively without mutating either input. Override values replace non-dictionary values.",
    initial: `
      def merge_config(base: dict, override: dict) -> dict:
          result = base.copy()
          result.update(override)
          return result
    `,
    reference: `
      from copy import deepcopy


      def merge_config(base: dict, override: dict) -> dict:
          result = deepcopy(base)
          for key, value in override.items():
              if isinstance(value, dict) and isinstance(result.get(key), dict):
                  result[key] = merge_config(result[key], value)
              else:
                  result[key] = deepcopy(value)
          return result
    `,
    tests: `
      import unittest

      from app import merge_config


      class MergeTests(unittest.TestCase):
          def test_recursive_merge_is_independent(self):
              base = {"model": {"name": "local", "tokens": 512}, "safe": True}
              override = {"model": {"tokens": 1024}, "safe": {"mode": "strict"}}
              merged = merge_config(base, override)
              self.assertEqual(
                  merged,
                  {"model": {"name": "local", "tokens": 1024}, "safe": {"mode": "strict"}},
              )
              merged["model"]["name"] = "changed"
              self.assertEqual(base["model"]["name"], "local")


      if __name__ == "__main__":
          unittest.main()
    `,
  }, SWE_BENCH_SOURCE),
  pythonCase({
    id: "python_half_open_window",
    category: "edge_case_repair",
    task:
      "Fix contains so time windows are half-open: the start is included and the end is excluded. Reject windows whose end is before their start.",
    initial: `
      from datetime import datetime


      def contains(start: datetime, end: datetime, instant: datetime) -> bool:
          return start <= instant <= end
    `,
    reference: `
      from datetime import datetime


      def contains(start: datetime, end: datetime, instant: datetime) -> bool:
          if end < start:
              return False
          return start <= instant < end
    `,
    tests: `
      import unittest
      from datetime import datetime, timedelta, timezone

      from app import contains


      class WindowTests(unittest.TestCase):
          def test_half_open_boundaries_and_invalid_window(self):
              start = datetime(2026, 1, 1, tzinfo=timezone.utc)
              end = start + timedelta(hours=1)
              self.assertTrue(contains(start, end, start))
              self.assertTrue(contains(start, end, end - timedelta(microseconds=1)))
              self.assertFalse(contains(start, end, end))
              self.assertFalse(contains(end, start, start))


      if __name__ == "__main__":
          unittest.main()
    `,
  }, SWE_BENCH_SOURCE),
  pythonCase({
    id: "python_atomic_balance_batch",
    category: "transaction_repair",
    task:
      "Repair apply_batch so all balance deltas are atomic. If any intermediate balance would be negative, raise ValueError and leave the original balances unchanged.",
    initial: `
      def apply_batch(balances: dict[str, int], operations: list[tuple[str, int]]) -> None:
          for account, delta in operations:
              balances[account] = balances.get(account, 0) + delta
              if balances[account] < 0:
                  raise ValueError("negative balance")
    `,
    reference: `
      def apply_batch(balances: dict[str, int], operations: list[tuple[str, int]]) -> None:
          updated = balances.copy()
          for account, delta in operations:
              updated[account] = updated.get(account, 0) + delta
              if updated[account] < 0:
                  raise ValueError("negative balance")
          balances.clear()
          balances.update(updated)
    `,
    tests: `
      import unittest

      from app import apply_batch


      class BatchTests(unittest.TestCase):
          def test_success_and_rollback(self):
              balances = {"a": 10, "b": 2}
              apply_batch(balances, [("a", -4), ("b", 3)])
              self.assertEqual(balances, {"a": 6, "b": 5})

              snapshot = balances.copy()
              with self.assertRaises(ValueError):
                  apply_batch(balances, [("a", 10), ("b", -20)])
              self.assertEqual(balances, snapshot)


      if __name__ == "__main__":
          unittest.main()
    `,
  }, SWE_BENCH_SOURCE),
];

const reactCases: CorpusCase[] = [
  reactCase({
    id: "react_accessible_alert",
    category: "accessibility_repair",
    task:
      "Repair Alert so it exposes an assertive alert region and uses both the shared alert class and a kind modifier without changing React's safe text rendering.",
    initial: `
      import React from "react";

      export interface AlertProps {
        message: string;
        kind: "info" | "error";
      }

      export function Alert({ message, kind }: AlertProps) {
        return <div className={kind}>{message}</div>;
      }
    `,
    reference: `
      import React from "react";

      export interface AlertProps {
        message: string;
        kind: "info" | "error";
      }

      export function Alert({ message, kind }: AlertProps) {
        return (
          <div
            role="alert"
            aria-live="assertive"
            className={\`alert alert--\${kind}\`}
          >
            {message}
          </div>
        );
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { Alert } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("alert semantics and safe content", () => {
        const html = renderToStaticMarkup(
          <Alert kind="error" message="<private>" />,
        );
        assert(html.includes('role="alert"'), html);
        assert(html.includes('aria-live="assertive"'), html);
        assert(html.includes('class="alert alert--error"'), html);
        assert(html.includes("&lt;private&gt;"), html);
      });
    `,
  }),
  reactCase({
    id: "react_casefold_filter",
    category: "component_logic_repair",
    task:
      "Fix FilteredList so filtering is case-insensitive and a no-match result renders a status message instead of an empty list.",
    initial: `
      import React from "react";

      export function FilteredList(
        { items, query }: { items: string[]; query: string },
      ) {
        const visible = items.filter((item) => item.includes(query));
        return <ul>{visible.map((item) => <li key={item}>{item}</li>)}</ul>;
      }
    `,
    reference: `
      import React from "react";

      export function FilteredList(
        { items, query }: { items: string[]; query: string },
      ) {
        const normalized = query.toLocaleLowerCase();
        const visible = items.filter((item) =>
          item.toLocaleLowerCase().includes(normalized)
        );
        if (visible.length === 0) {
          return <p role="status">No matches</p>;
        }
        return <ul>{visible.map((item) => <li key={item}>{item}</li>)}</ul>;
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { FilteredList } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("case-insensitive matches", () => {
        const html = renderToStaticMarkup(
          <FilteredList items={["Alpha", "beta"]} query="AL" />,
        );
        assert(html.includes("Alpha"), html);
        assert(!html.includes("beta"), html);
      });

      Deno.test("empty state is announced", () => {
        const html = renderToStaticMarkup(
          <FilteredList items={["Alpha"]} query="missing" />,
        );
        assert(html.includes('role="status"'), html);
        assert(html.includes("No matches"), html);
      });
    `,
  }),
  reactCase({
    id: "react_counter_boundaries",
    category: "component_state_repair",
    task:
      "Repair Counter markup so decrement is disabled at the minimum, increment is disabled at the maximum, and the current value remains exposed as output.",
    initial: `
      import React from "react";

      export function Counter(
        { value, min, max }: { value: number; min: number; max: number },
      ) {
        return (
          <div>
            <button aria-label="Decrement">-</button>
            <output>{value}</output>
            <button aria-label="Increment">+</button>
          </div>
        );
      }
    `,
    reference: `
      import React from "react";

      export function Counter(
        { value, min, max }: { value: number; min: number; max: number },
      ) {
        return (
          <div>
            <button aria-label="Decrement" disabled={value <= min}>-</button>
            <output>{value}</output>
            <button aria-label="Increment" disabled={value >= max}>+</button>
          </div>
        );
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { Counter } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("counter disables the correct boundary action", () => {
        const minimum = renderToStaticMarkup(<Counter value={0} min={0} max={2} />);
        assert(minimum.includes('<button aria-label="Decrement" disabled="">'), minimum);
        assert(!minimum.includes('<button aria-label="Increment" disabled="">'), minimum);
        assert(minimum.includes("<output>0</output>"), minimum);

        const maximum = renderToStaticMarkup(<Counter value={2} min={0} max={2} />);
        assert(!maximum.includes('<button aria-label="Decrement" disabled="">'), maximum);
        assert(maximum.includes('<button aria-label="Increment" disabled="">'), maximum);
      });
    `,
  }),
  reactCase({
    id: "react_field_error_linkage",
    category: "accessibility_repair",
    task:
      "Fix Field so an error marks the input invalid, links it to a stable error element, and exposes that error as an alert. Do not render an error element when there is no error.",
    initial: `
      import React from "react";

      export function Field(
        { id, label, error }: { id: string; label: string; error?: string },
      ) {
        return (
          <label htmlFor={id}>
            {label}
            <input id={id} />
            {error && <span>{error}</span>}
          </label>
        );
      }
    `,
    reference: `
      import React from "react";

      export function Field(
        { id, label, error }: { id: string; label: string; error?: string },
      ) {
        const errorId = \`\${id}-error\`;
        return (
          <label htmlFor={id}>
            {label}
            <input
              id={id}
              aria-invalid={error ? "true" : undefined}
              aria-describedby={error ? errorId : undefined}
            />
            {error && <span id={errorId} role="alert">{error}</span>}
          </label>
        );
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { Field } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("error is linked to the input", () => {
        const html = renderToStaticMarkup(<Field id="name" label="Name" error="Required" />);
        assert(html.includes('aria-invalid="true"'), html);
        assert(html.includes('aria-describedby="name-error"'), html);
        assert(html.includes('id="name-error" role="alert"'), html);
      });

      Deno.test("valid field omits error semantics", () => {
        const html = renderToStaticMarkup(<Field id="name" label="Name" />);
        assert(!html.includes("aria-invalid"), html);
        assert(!html.includes("name-error"), html);
      });
    `,
  }),
  reactCase({
    id: "react_status_badge_mapping",
    category: "component_logic_repair",
    task:
      "Repair StatusBadge so each machine status has stable human text and a status modifier class while retaining the shared status class.",
    initial: `
      import React from "react";

      export type Status = "queued" | "running" | "failed" | "done";

      export function StatusBadge({ status }: { status: Status }) {
        return <span>{status}</span>;
      }
    `,
    reference: `
      import React from "react";

      export type Status = "queued" | "running" | "failed" | "done";

      const labels: Record<Status, string> = {
        queued: "Waiting",
        running: "In progress",
        failed: "Failed",
        done: "Complete",
      };

      export function StatusBadge({ status }: { status: Status }) {
        return <span className={\`status status--\${status}\`}>{labels[status]}</span>;
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { Status, StatusBadge } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("all statuses have labels and modifiers", () => {
        const expected: Array<[Status, string]> = [
          ["queued", "Waiting"],
          ["running", "In progress"],
          ["failed", "Failed"],
          ["done", "Complete"],
        ];
        for (const [status, label] of expected) {
          const html = renderToStaticMarkup(<StatusBadge status={status} />);
          assert(html.includes(\`class="status status--\${status}"\`), html);
          assert(html.includes(\`>\${label}<\`), html);
        }
      });
    `,
  }),
  reactCase({
    id: "react_task_progress_summary",
    category: "accessibility_repair",
    task:
      "Repair TaskSummary so it renders singular/plural text from total and exposes the completed count through a progressbar with explicit minimum and maximum values.",
    initial: `
      import React from "react";

      export function TaskSummary(
        { completed, total }: { completed: number; total: number },
      ) {
        return <p>{completed} of {total} task complete</p>;
      }
    `,
    reference: `
      import React from "react";

      export function TaskSummary(
        { completed, total }: { completed: number; total: number },
      ) {
        const noun = total === 1 ? "task" : "tasks";
        return (
          <div
            role="progressbar"
            aria-valuemin={0}
            aria-valuemax={total}
            aria-valuenow={completed}
          >
            {completed} of {total} {noun} complete
          </div>
        );
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { TaskSummary } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("summary pluralizes and exposes progress", () => {
        const singular = renderToStaticMarkup(<TaskSummary completed={1} total={1} />);
        assert(singular.includes("1 of 1 task complete"), singular);
        const plural = renderToStaticMarkup(<TaskSummary completed={2} total={3} />);
        assert(plural.includes("2 of 3 tasks complete"), plural);
        assert(plural.includes('role="progressbar"'), plural);
        assert(plural.includes('aria-valuemin="0"'), plural);
        assert(plural.includes('aria-valuemax="3"'), plural);
        assert(plural.includes('aria-valuenow="2"'), plural);
      });
    `,
  }),
  reactCase({
    id: "react_tabs_semantics",
    category: "accessibility_repair",
    task:
      "Repair Tabs markup so the tab list, selected and unselected tabs, keyboard tab stops, and selected tab panel are linked with stable ARIA ids.",
    initial: `
      import React from "react";

      export interface Tab {
        id: string;
        label: string;
        content: string;
      }

      export function Tabs({ tabs, selectedId }: { tabs: Tab[]; selectedId: string }) {
        const selected = tabs.find((tab) => tab.id === selectedId);
        return (
          <div>
            {tabs.map((tab) => <button key={tab.id}>{tab.label}</button>)}
            <section>{selected?.content}</section>
          </div>
        );
      }
    `,
    reference: `
      import React from "react";

      export interface Tab {
        id: string;
        label: string;
        content: string;
      }

      export function Tabs({ tabs, selectedId }: { tabs: Tab[]; selectedId: string }) {
        const selected = tabs.find((tab) => tab.id === selectedId);
        return (
          <div>
            <div role="tablist">
              {tabs.map((tab) => {
                const active = tab.id === selectedId;
                return (
                  <button
                    key={tab.id}
                    id={\`tab-\${tab.id}\`}
                    role="tab"
                    aria-selected={active}
                    aria-controls={\`panel-\${tab.id}\`}
                    tabIndex={active ? 0 : -1}
                  >
                    {tab.label}
                  </button>
                );
              })}
            </div>
            {selected && (
              <section
                id={\`panel-\${selected.id}\`}
                role="tabpanel"
                aria-labelledby={\`tab-\${selected.id}\`}
              >
                {selected.content}
              </section>
            )}
          </div>
        );
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { Tabs } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("tabs and panel are linked", () => {
        const html = renderToStaticMarkup(
          <Tabs
            selectedId="two"
            tabs={[
              { id: "one", label: "One", content: "First" },
              { id: "two", label: "Two", content: "Second" },
            ]}
          />,
        );
        assert(html.includes('role="tablist"'), html);
        assert(html.includes('id="tab-one" role="tab" aria-selected="false" aria-controls="panel-one" tabindex="-1"'), html);
        assert(html.includes('id="tab-two" role="tab" aria-selected="true" aria-controls="panel-two" tabindex="0"'), html);
        assert(html.includes('id="panel-two" role="tabpanel" aria-labelledby="tab-two"'), html);
        assert(html.includes("Second"), html);
        assert(!html.includes("First"), html);
      });
    `,
  }),
  reactCase({
    id: "react_pagination_boundaries",
    category: "component_logic_repair",
    task:
      "Repair Pagination so page display is clamped to a valid range, previous and next buttons are disabled at their respective boundaries, and the navigation has an accessible label.",
    initial: `
      import React from "react";

      export function Pagination(
        { page, totalPages }: { page: number; totalPages: number },
      ) {
        return (
          <nav>
            <button>Previous</button>
            <span>Page {page} of {totalPages}</span>
            <button>Next</button>
          </nav>
        );
      }
    `,
    reference: `
      import React from "react";

      export function Pagination(
        { page, totalPages }: { page: number; totalPages: number },
      ) {
        const maximum = Math.max(1, totalPages);
        const current = Math.min(maximum, Math.max(1, page));
        return (
          <nav aria-label="Pagination">
            <button disabled={current === 1}>Previous</button>
            <span>Page {current} of {maximum}</span>
            <button disabled={current === maximum}>Next</button>
          </nav>
        );
      }
    `,
    tests: `
      import React from "react";
      import { renderToStaticMarkup } from "react-dom/server";
      import { Pagination } from "../src/Component.tsx";

      function assert(condition: boolean, message: string) {
        if (!condition) throw new Error(message);
      }

      Deno.test("pagination clamps and disables boundaries", () => {
        const first = renderToStaticMarkup(<Pagination page={0} totalPages={3} />);
        assert(first.includes('<nav aria-label="Pagination">'), first);
        assert(first.includes("Page 1 of 3"), first);
        assert(first.includes('<button disabled="">Previous</button>'), first);
        assert(!first.includes('<button disabled="">Next</button>'), first);

        const last = renderToStaticMarkup(<Pagination page={9} totalPages={3} />);
        assert(last.includes("Page 3 of 3"), last);
        assert(!last.includes('<button disabled="">Previous</button>'), last);
        assert(last.includes('<button disabled="">Next</button>'), last);
      });
    `,
  }),
];

export const corpus: TaskCorpus = {
  version: 1,
  cases: [...rustCases, ...pythonCases, ...reactCases],
};

export default corpus;
