export const SCROLL_THRESHOLD = 80;

export const TOOL_FRIENDLY_NAMES: Record<string, string> = {
  read_file: "Read file",
  inspect_change: "Inspect change",
  glob: "List files",
  ripgrep: "Search code",
  search: "Search",
  web_search: "Web search",
  web_fetch: "Fetch URL",
  git_log: "Git log",
  session_changes: "Review recent work",
  session_title: "Set title",
  todo: "Manage todos",
  skill_search: "Search skills",
  skill: "Load skill",
  ask_user: "Ask user",
  run_command: "Run command",
  run_task: "Run project task",
  run_check: "Run acceptance check",
  lsp_proactive_diagnostics: "Inspect language diagnostics",
  write_file: "Create file",
  replace_file: "Replace file",
  edit_file: "Edit file",
  apply_patch: "Apply patch",
  mv: "Move/rename",
  rm: "Remove",
  git_commit: "Commit changes",
  git_revert: "Revert commit",
  memory_search: "Search project memory",
  memory_read: "Read project memory",
  memory_propose: "Propose project memory",
  memory_supersede: "Supersede project memory",
  sub_agent: "Sub-agent",
  propose_delivery: "Propose a delivery",
  start_delivery: "Start delivery",
  propose_goal: "Propose a goal",
  start_goal: "Start goal",
  goal_status: "Check goal status",
  goal_pause: "Pause goal",
  goal_request_amendment: "Request goal change",
  goal_request_budget: "Request goal budget",
  submit_plan: "Submit delivery plan",
  submit_plan_review: "Review delivery plan",
  submit_implementation: "Report implementation",
  submit_code_review: "Submit code review",
  request_replan: "Request a new plan",
};

export const TOOL_ICONS: Record<string, string> = {
  read_file: "bi bi-file-earmark-text",
  inspect_change: "bi bi-file-earmark-diff",
  glob: "bi bi-files",
  ripgrep: "bi bi-search",
  search: "bi bi-search",
  web_search: "bi bi-globe",
  web_fetch: "bi bi-link",
  git_log: "bi bi-clock-history",
  session_changes: "bi bi-clock-history",
  session_title: "bi bi-type",
  todo: "bi bi-check2-square",
  skill_search: "bi bi-bookmark-star",
  skill: "bi bi-file-earmark-code",
  ask_user: "bi bi-person-circle",
  run_command: "bi bi-play-circle",
  run_task: "bi bi-play-btn",
  run_check: "bi bi-shield-check",
  lsp_proactive_diagnostics: "bi bi-braces-asterisk",
  write_file: "bi bi-file-earmark-plus",
  replace_file: "bi bi-file-earmark-arrow-up",
  edit_file: "bi bi-pencil-square",
  apply_patch: "bi bi-diff",
  mv: "bi bi-graph-up-arrow",
  rm: "bi bi-trash",
  git_commit: "bi bi-git",
  git_revert: "bi bi-x-octagon",
  memory_search: "bi bi-search-heart",
  memory_read: "bi bi-journal-text",
  memory_propose: "bi bi-journal-plus",
  memory_supersede: "bi bi-journal-x",
  sub_agent: "bi bi-people",
  propose_delivery: "bi bi-box-seam",
  start_delivery: "bi bi-box-arrow-in-right",
  propose_goal: "bi bi-bullseye",
  start_goal: "bi bi-play-circle",
  goal_status: "bi bi-activity",
  goal_pause: "bi bi-pause-circle",
  goal_request_amendment: "bi bi-pencil-square",
  goal_request_budget: "bi bi-speedometer2",
  submit_plan: "bi bi-clipboard2-check",
  submit_plan_review: "bi bi-clipboard2-pulse",
  submit_implementation: "bi bi-code-square",
  submit_code_review: "bi bi-shield-check",
  request_replan: "bi bi-arrow-repeat",
};
